# 1) Build step
FROM node:20-alpine AS build
WORKDIR /app

# Install deps (better caching)
COPY package*.json ./
RUN npm ci

# Copy source and build
COPY . .
RUN npm run build

# 2) Serve step
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80