name: FrontendCI

on:
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: npm install
        working-directory: bmthwebsite/bmth-frontend/bmth-frontend
      - run: npm test
        working-directory: bmthwebsite/bmth-frontend/bmth-frontend